# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcpx < Formula
  desc "Universal MCP relay that aggregates multiple MCP servers behind meta-tools"
  homepage "https://github.com/fieldjoshua/mcp-relay"
  version "1.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fieldjoshua/mcp-relay/releases/download/v1.2.0/mcpx_1.2.0_darwin_amd64.tar.gz"
      sha256 "5d244152470f054e49eb922296280ae220e35a168c5253cdee934a1aec2abeb6"

      def install
        bin.install "mcpx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fieldjoshua/mcp-relay/releases/download/v1.2.0/mcpx_1.2.0_darwin_arm64.tar.gz"
      sha256 "07732ea29d820f0da67b076ac944ff2f9650a94cd79e9cd22a887723c71f641e"

      def install
        bin.install "mcpx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fieldjoshua/mcp-relay/releases/download/v1.2.0/mcpx_1.2.0_linux_amd64.tar.gz"
      sha256 "05fa5d7975fb96f8acc5ade78a3db0738dbf7fe7b6a9e1201f26b042f2c75506"
      def install
        bin.install "mcpx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fieldjoshua/mcp-relay/releases/download/v1.2.0/mcpx_1.2.0_linux_arm64.tar.gz"
      sha256 "f6fde7878ca2007b68372e21a470511046ed15fb01722932a4f0b3251f4b9894"
      def install
        bin.install "mcpx"
      end
    end
  end

  test do
    system "#{bin}/mcpx", "version"
  end
end
